# Generated by Django 5.0.1 on 2024-02-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('ram_size', models.CharField(max_length=2)),
                ('rom_size', models.CharField(max_length=4)),
                ('price', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['-pk'],
            },
        ),
    ]
