# Generated by Django 5.0.1 on 2024-02-07 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
