# Generated by Django 5.0.1 on 2024-02-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_product_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ram_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rom_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
    ]
