# Generated by Django 5.0.1 on 2024-02-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_product_ram_size_remove_product_rom_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
